#!/usr/bin/env python3
# Copyright (c) 2026 vivo Mobile Communication Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate a Rust source file containing the ELF binary as a byte array.

Usage:
    gen_bytes.py <elf_path> <output_path>

Reads the ELF binary at <elf_path> and writes a .rs file at <output_path>
with a `pub(crate) const FIRST_ELF_BYTES: &[u8] = &[...]` containing the raw
ELF bytes, ready for `include!()` in the kernel crate.
"""

import sys
import os


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <elf_path> <output_path>", file=sys.stderr)
        sys.exit(1)

    elf_path = sys.argv[1]
    output_path = sys.argv[2]

    with open(elf_path, "rb") as f:
        data = f.read()

    # Format as a Rust byte array with 16 bytes per line for readability.
    lines = []
    lines.append("// Auto-generated by gen_bytes.py — do not edit manually.")
    lines.append("// Contains the ELF binary for the first user-space process.")
    lines.append("")
    lines.append("pub(crate) const FIRST_ELF_BYTES: &[u8] = &[")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_strs = ", ".join(f"0x{b:02x}u8" for b in chunk)
        lines.append(f"    {hex_strs},")
    lines.append("];")
    lines.append("")

    out_dir = os.path.dirname(output_path)
    if out_dir and not os.path.exists(out_dir):
        os.makedirs(out_dir)

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {output_path} ({len(data)} bytes)")


if __name__ == "__main__":
    main()